### ISSUE TITLE
Python3 can't sort when similar elements have weird suffixes

### ISSUE THREAD

**Issue by glajchs** [alimony/sublime-sort-numerically#10]
Interestingly this seems to only be a problem in python3, which I think sublime3 is using.  I've boiled my issue down to the following file, which isn't getting sorted numerically:

>2 a
>1 b2
>1 b.

In sublime it doesn't sort the list at all.  This came up when I was sorting lines that essentially had 2 columns.  Column 1 was an integer number of varying length, and column 2 was "the rest".  Basically for my use case, "the rest" was some metadata showing me what that line represented.  Sometimes that metadata had numbers and periods in it.

When I made a test for it and tested it in tests.py, it passed!  Until i figured out that my command line was using python 2.7.12, and sublime must be using my python 3 binary, 3.5.2.  Once I ran the tests using python3 tests.py, it failed with:

>....E.....
>======================================================================
>ERROR: test_sort_with_alphanumeric_partial_formatting (__main__.TestSortNumerically)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "tests.py", line 105, in test_sort_with_alphanumeric_partial_formatting
>    self.assertEqual(sort_lines(input_lines), expected_output_lines)
>  File "/home/scott/sources/sublime-sort-numerically/sort_numerically.py", line 26, in sort_lines
>    return sorted(input_lines, key=alphanum_key)
>TypeError: unorderable types: str() < float()
>
>----------------------------------------------------------------------
>Ran 10 tests in 0.001s
>
>FAILED (errors=1)

here's the test I tried to add:

>        def test_sort_with_alphanumeric_partial_formatting(self):
>            input_lines = [
>                '2 a',
>                '1 b2',
>                '1 b.'
>            ]
>            expected_output_lines = [
>                '1 b2',
>                '1 b.',
>                '2 a'
>            ]
>            self.assertEqual(sort_lines(input_lines), expected_output_lines)

**Comment by alimony** [comment]
Thank you so much for a thorough bug report, this is definitely enough for me to get to work and sort (hah) this out as soon as possible. Will let you know.

**Comment by alimony** [comment]
I have some working code, essentially moving to natsort for robust and predictable behaviour.

It will take some time to push the changes though, because I need to get a dependency into the Package Control channel, here's the PR for that: https://github.com/wbond/package_control_channel/pull/6891

Will keep you posted.

**Comment by alimony** [comment]
I've pushed all my changes in 1919b9fff45f759b883a325b963c20b8d82328a2 and my own tests yield proper results and passing tests in both Python 2/3 and Sublime Text 2/3.

Could you help me test it one last time @glajchs? Just download the master branch as a zip using [this link](https://github.com/alimony/sublime-sort-numerically/archive/master.zip), then uninstall the existing plugin, and add the downloaded one manually to your Packages folder. Let me know if you need more help, would appreciate your help so much!

**Comment by glajchs** [comment]
Sorry I didn't get around to this until now, but I just installed your updated version and it worked great.  Thanks! :+1:

**Comment by alimony** [comment]
Fixed in [1.0.3](https://github.com/alimony/sublime-sort-numerically/releases/tag/1.0.3) which should now be available through Package Control. Thanks!
