### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [alimony/sublime-sort-numerically#11]
I don't think this works as it currently exists. The imports are broken. I'd be glad to make a PR if you're interested. Thanks!

**Comment by alimony** [comment]
That's odd, it seems like the local import is broken:

https://github.com/alimony/sublime-sort-numerically/blob/master/SortNumericallyCommand.py#L11

My guess would be that something has changed in how Package Control looks for imports, loading order etc. Nothing has changed in the plugin itself or its underlying `natsort` dependency.

If you want to have a look at this it would be greatly appreciated!

**Comment by i-s-o-g-r-a-m** [comment]
@alimony Thanks for the reply.

It's odd: when I tried to reproduce this today, it started working – no import problem.

I'll close this issue and if it starts happening again I will re-open. Thank you!
